#include "cpu/exec/helper.h"


setcc_helper(a0nbe, (!cpu.CF && !cpu.ZF))
setcc_helper(ae0nb0nc, (!cpu.CF))
setcc_helper(b0c0nae, (cpu.CF))
setcc_helper(be0na, (cpu.CF || cpu.ZF))
// setcc_helper(c, (cpu.CF)))
setcc_helper(e0z, (cpu.ZF))
// ? 
setcc_helper(g0nle, (!cpu.ZF && cpu.SF == cpu.OF))
setcc_helper(ge0nl, (cpu.SF == cpu.OF))
setcc_helper(l0nge, (cpu.SF != cpu.OF))
setcc_helper(le0ng, (cpu.ZF || cpu.SF != cpu.OF))
// setcc_helper(na, (cpu.CF)))
// setcc_helper(nae, (cpu.CF)))
// setcc_helper(nb, (!cpu.CF)))
// setcc_helper(nbe, (!cpu.CF) && !cpu.ZF)))
// setcc_helper(nc, (!cpu.CF)))
setcc_helper(ne0nz, (!cpu.ZF))
// setcc_helper(ng, (cpu.ZF) || cpu.SF) != cpu.OF)))
// setcc_helper(nge, (cpu.SF) != cpu.OF)))
// setcc_helper(nl, (cpu.SF) == cpu.OF)))
// setcc_helper(nle, (cpu.ZF) && cpu.SF) != cpu.OF)))
setcc_helper(no, (!cpu.OF))
setcc_helper(np0po, (!cpu.PF))
setcc_helper(ns, (!cpu.SF))
// setcc_helper(nz, (!cpu.ZF)))
setcc_helper(o, (cpu.OF))
setcc_helper(p0pe, (cpu.PF))
// setcc_helper(pe, (cpu.PF)))
// setcc_helper(po, (!cpu.PF)))
setcc_helper(s, (cpu.SF))
// setcc_helper(z, (cpu.ZF)))

#undef re